# Generated by Django 5.2.7 on 2025-12-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyHub', '0002_alter_resource_options_resource_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='StudyHub.subject'),
        ),
    ]
